nohup: 忽略输入
INFO:root:start with arguments Namespace(batch_size=256, benchmark=0, bottle_neck=1, data_nthreads=4, data_train='train.lst', data_val='val.lst', deform=0, dilpat='', disp_batches=20, dtype='float32', expansion=0.5, gpus='0,1,2,3,4,5,6,7', image_shape='3,224,224', irv2=False, kv_store='device', lastout=7, load_epoch=None, lr=0.1, lr_factor=0.1, lr_step_epochs='30,50,70', max_random_aspect_ratio=0.25, max_random_h=36, max_random_l=50, max_random_rotate_angle=10, max_random_s=50, max_random_scale=1, max_random_shear_ratio=0.1, min_random_scale=1.0, model_prefix='/data1/deepinsight/mxnet_models/imagenet1l/resnext50_96x4d1ov2xp/', mom=0.9, monitor=0, network='irnext', num_classes=1000, num_epochs=80, num_examples=1281167, num_group=96, num_layers=50, optimizer='sgd', outfeature=1536, pad_size=0, random_crop=1, random_mirror=1, rgb_mean='123.68,116.779,103.939', test_io=0, top_k=5, wd=0.0001)
Traceback (most recent call last):
  File "train_imagenet_cls.py", line 54, in <module>
    fit.fit(args, sym, data.get_rec_iter)
  File "/home/deepinsight/frankwang/Deformable-ConvNets/deeplab/common/fit.py", line 107, in fit
    (train, val) = data_loader(args, kv)
  File "/home/deepinsight/frankwang/Deformable-ConvNets/deeplab/common/data.py", line 174, in get_rec_iter
    part_index          = rank)
  File "/home/deepinsight/.local/lib/python2.7/site-packages/mxnet/image.py", line 568, in __init__
    with open(path_imglist) as fin:
IOError: [Errno 2] No such file or directory: 'train.lst'
